backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /public
editor:
  preview: false

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Feature Image", name: "feature", widget: "image"}
      - {label: "Video Link", name: "video", widget: "link"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "select", options: [{label: "Melvin Musehani", value: "melvin"}, {label: "Nokwanda Maranjane", value: "nokwanda"}]}
      - {label: "Tags (Separate by commas)", name: "tags", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
  - name: "templates"
    label: "Templates"
    folder: "content/templates"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Feature Image", name: "feature", widget: "image"}
      - {label: "Video Link", name: "video", widget: "link"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Tags (Separate by commas)", name: "tags", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
  - name: "tutorials"
    label: "Tutorials"
    folder: "content/tutorials"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Feature Image", name: "feature", widget: "image"}
      - {label: "Video Link", name: "video", widget: "link"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "select", options: [{label: "Melvin Musehani", value: "melvin"}, {label: "Nokwanda Maranjane", value: "nokwanda"}]}
      - {label: "Tags (Separate by commas)", name: "tags", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}